services:
  postgres:
    image: postgres:14
    container_name: catgram_postgres
    environment:
      POSTGRES_DB: catgram_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: