networks:
  kittyBotNetwork:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: catgram_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      kittyBotNetwork:

  bot:
    build:
      context: .
      dockerfile: ./TelegramService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    volumes:
      - cat_photos:/app/photos
    networks:
      kittyBotNetwork:

  catservice:
    build:
      context: .
      dockerfile: ./CatService/Dockerfile
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/catgram_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true

      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    volumes:
      - cat_photos:/app/photos
    networks:
      kittyBotNetwork:

  adminservice:
    build:
      context: .
      dockerfile: ./AdminService/Dockerfile
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/catgram_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      kittyBotNetwork:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      kittyBotNetwork:


volumes:
  postgres_data:
  cat_photos:
