server:
  port: 8080

spring:
  application:
    name: adminservice
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catgram_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:your_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

admin:
  user: ${ADMIN_USER:admin}
  password: ${ADMIN_PASSWORD:admin}
